### ISSUE TITLE
Inserting backtick inserts a second backtick

### ISSUE THREAD

**Issue by zl4bv** [jrsconfitto/language-powershell#37]
Currently, pressing <kbd>`</kbd>, <kbd>n</kbd> results in

```
`n`
```

I expect that pressing <kbd>`</kbd>, <kbd>n</kbd> results in

```
`n
```

It makes sense to insert a second backtick when writing markdown since it's used for code spans, but not at all useful in PowerShell since backticks denote escaped characters.

**Comment by jugglingnutcase** [comment]
Thanks for letting me know!

i'll take a look and see what i can do about disabling that behavior for backticks.

**Comment by jugglingnutcase** [comment]
i've opened an issue in atom/bracket-matcher#121 to see if there's a way this grammar can turn that behavior off.

in the meantime, i think the best workaround may be to turn off the automatic quote insertion in the bracket-matcher settings...

**Comment by zl4bv** [comment]
Thanks @jrsconfitto! Closing, as it looks like this was solved by atom/bracket-matcher#249
