### ISSUE TITLE
Extra Carriage Returns / Added Symbols

### ISSUE THREAD

**Issue by nloiselle** [jrsconfitto/language-powershell#56]
I am having an issue where my PowerShell scripts that I clone from Git repositories are displayed with extra carriage returns, and each function starts with '??' symbols at the top of the file.  
![screen shot 2017-02-22 at 8 47 15 am](https://cloud.githubusercontent.com/assets/22030664/23214262/fe8cf7c4-f8db-11e6-8ed9-023fe1fd5d8b.png)

**Comment by jrsconfitto** [comment]
Hi, thanks for the report!

i'm probably speaking out of ignorance here, but i think those question mark icons may be [UTF BOMs](https://en.wikipedia.org/wiki/Byte_order_mark)? Here's a helpful [SO post on the subject](http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom).

For the extra newlines, what do you see if you "Show invisibles"? (Again, possible ignorance here...)

Can you point me to any of these repositories so i can check out the files myself? i think the combination of the (possible?) BOM plus the extra newline characters may mean the file is formatted for UNIX and not windows, but i'm unsure of this.

**Comment by nloiselle** [comment]
So I looked more into the UTF encoding, and these functions that are diplaying incorrectly were all generally created in Powershell ISE, which encodes in UTF-16LE.  Is there a way to change the encoding for this package to open in that by default, or is that a core functionality?

When I select "Show invisibles" these are the characters that are being displayed:

![image](https://cloud.githubusercontent.com/assets/22030664/23216071/aacded76-f8e2-11e6-8d2b-83584a533b37.png)

**Comment by nloiselle** [comment]
It was the encoding.  I was able to find the Core setting to adjust it to always open in UTF-16LE, and PowerShell functions display correctly now.  I'll close this out, thanks for jumping in on this.

**Comment by jrsconfitto** [comment]
No problem 😄 

I didn't know that ps1s in ISE were UTF-16LE, thanks for that!
