### ISSUE TITLE
tab type setting is ignored

### ISSUE THREAD

**Issue by kelbyers** [jrsconfitto/language-powershell#60]
The settings for soft or auto tab types seem to be ignored. When editing a file with the tab type set to "soft", pressing the tab key always inserts a tab character.

The auto tab type may or may not correctly detect whether the source file is using spaces or tabs, but has the same result as choosing "soft" in the settings: pressing the tab key (or using autoindent) inserts a tab character instead of spaces.

**Comment by jrsconfitto** [comment]
Hi @kelbyers, thanks for the report and i'm sorry i took so long to respond.

i'm not seeing the behavior you describe. i'll show you want i see and please let me know if i've missed something!

In the language-powershell package settings (working off version 4.0.0) i have set 'soft tabs' with a tab length of 4:

![image](https://user-images.githubusercontent.com/238079/35570914-9ba1991e-059e-11e8-80e1-0c2072a3cfce.png)

Then, when hitting the tab key, i get spaces:

![image](https://user-images.githubusercontent.com/238079/35571005-e395cf60-059e-11e8-825d-12a7ef9d16f2.png)

When i switched to 'hard tabs' i see tabs inserted into the editor.

Are you still experiencing this issue?

**Comment by kelbyers** [comment]
I am still seeing this issue.

![image](https://user-images.githubusercontent.com/1743077/35597766-94620692-05e5-11e8-8a7f-e92a7ad062f1.png)

Added a new line after line 37, and pressed the tab key, which inserted a tab:
![image](https://user-images.githubusercontent.com/1743077/35597804-be3fa384-05e5-11e8-903f-995ab0012bd5.png)

**Comment by jrsconfitto** [comment]
Thanks, i'll take a deeper look.

**Comment by kelbyers** [comment]
Well, I decided to see if some other package may be interfering with this, and messed around with a fresh install of atom and moving all my packages out. After trying several things and seeing the autoindent work correctly, I looked at my previous config.cson file compared to the fresh install. Somehow, I had turned off the Autoindent setting at the very top of the configuration.

After resetting the configuration of this package to defaults, everything is working as expected.

**Comment by jrsconfitto** [comment]
Thanks for taking another look!

I had given this some attention on and off in the past week, but wasn’t able to get very far.

I thought I was able to find a way to (intermittently) reproduce the issue by converting the whole file between tabs and spaces, but this led me to the conclusion that this package wasn’t the result of the behavior. This package is very similar to other language packages.

I was set to look into where to report something like this up the chain but didn’t know enough about the internals to do that, I’ll pick it up again if things like this come up again.

Thanks again for the report,
James
