### ISSUE TITLE
Investigate writing a new PowerShell grammar for Tree Sitter

### ISSUE THREAD

**Issue by daviwil** [jrsconfitto/language-powershell#61]
One thing that might be of interest to you is the new [Tree Sitter](https://github.com/tree-sitter/tree-sitter) parsing system that [recently got merged](https://github.com/atom/atom/pull/16299) into Atom's master branch (coming to Atom Beta 1.25 next month).  This will enable a much more faithful highlighting of PowerShell once a Tree Sitter grammar is written for it, plus some other potentially nice editing features that having an in-editor AST would allow.  I think it'd be great for language-powershell to be the place where this new grammar lives!

/cc @Jaykul

**Comment by jrsconfitto** [comment]
OK, i've been on jury duty which afforded me some time to start tackling this... check it out [tree-sitter-powershell](https://github.com/jrsconfitto/tree-sitter-powershell). It's really rough at this point, but i think i'm starting to get a sense of how to write a tree-sitter grammar.

I'm happy to take contributions and issues 👍
