### ISSUE TITLE
Syntax Highlighting for "Where-Object"

### ISSUE THREAD

**Issue by megan201296** [jrsconfitto/language-powershell#64]
When I use "Where-Object" it does not highlight in turquoise like the other cmdlets. Instead "Where" highlights purple and "-Object" highlights gray. Not sure if this is purposeful but seems like it should highlight turquoise like all other cmdlets.

**Comment by jrsconfitto** [comment]
Thanks for the report, i'll take a look.

**Comment by jrsconfitto** [comment]
This is a duplicate of (recently revived) #53. I hope to move back to PowerShell/EditorSyntax since it's looking great right now.

**Comment by jrsconfitto** [comment]
Should be taken care of by #65, thanks for your patience.
