### ISSUE TITLE
PS v6 approved verb highlighting

### ISSUE THREAD

**Issue by Akaizoku** [jrsconfitto/language-powershell#66]
The list of approved verb has been updated in PowerShell v6 to include the following verbs:

Verb (alias) | Action | Comments
-- | -- | --
Build (bd) | Creates an artifact (usually a binary or document) out of some set of input files (usually source code or declarative documents) | This verb was added in PowerShell v6
Deploy(dp) | Sends an application, website, or solution to a remote target[s] in such a way that a consumer of that solution can access it after deployment is complete | This verb was added in PowerShell v6

It seems that the grammar has already been updated on [PowerShell/EditorSyntax](https://github.com/PowerShell/EditorSyntax) (see [issue #147](https://github.com/PowerShell/EditorSyntax/issues/147)).

Could you update the package with the new grammar?

**Comment by jrsconfitto** [comment]
OK, i've published a new version that should have added these verbs. If there are any issues, please let me know!
